# Generated by Django 5.2.17 on 2026-09-15 08:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("staff_id", models.CharField(max_length=60, unique=True)),
                ("surname", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=150)),
                ("other_names", models.CharField(blank=True, max_length=200)),
                ("gender", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=200)),
                ("grade_level", models.CharField(blank=True, max_length=100)),
                ("division", models.CharField(blank=True, max_length=200)),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "appraiser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="employees.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["staff_id", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("user", models.F("appraiser")), _negated=True),
                        name="employee_appraiser_not_self",
                    )
                ],
            },
        ),
    ]
